apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-agent
  namespace: k8s-ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-agent
  template:
    metadata:
      labels:
        app: k8s-agent
    spec:
      serviceAccountName: k8s-agent

      containers:
        - name: agent
          image: ghcr.io/yakovm44/k8s-ai-agent:11821b6fe52ee78714af3dd5649f4fccb9adffc2
          ports:
            - containerPort: 8000
