apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-agent
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-agent
  template:
    metadata:
      labels:
        app: k8s-agent
    spec:
      serviceAccountName: k8s-agent

      containers:
        - name: agent
          image: ghcr.io/yakovm44/k8s-ai-agent:c3ecc309e34a2f808823d2e4ed354edc50fa9806
          ports:
            - containerPort: 8000
