apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/yakovm44/argocd.git
      revision: HEAD
      directories:
      # סורק את כל התיקיות הישירות מתחת ל-dev, stg ו-prd
      - path: guestbook/dev/*
      - path: guestbook/stg/*
      - path: guestbook/prd/*

  template:
    metadata:
      # השם יורכב מהתיקייה של הסביבה ומשם האפליקציה (למשל: dev-my-app)
      name: '{{index .path.segments 1}}-{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/yakovm44/argocd.git
        targetRevision: HEAD
        # הנתיב הדינמי לכל אפליקציה שנמצאה
        path: '{{.path.path}}'
      destination:
        name: '{{index .path.segments 1}}'
#        server: https://kubernetes.default.svc
        namespace: guestbook
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true